import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <nav className="p-4 bg-white shadow-md flex gap-4">
          <Link href="/" className="text-blue-500">
            Home
          </Link>
          <Link href="/about" className="text-blue-500">
            About
          </Link>
        </nav>
        <main className="p-10">{children}</main>
      </body>
    </html>
  );
}
